### ISSUE TITLE
Update to `brotli2`.

### ISSUE THREAD

**Issue by Protryon** [Nemo157/async-compression#83]
The usage of the `brotli` crate creates an ABI incompatibility with `brotli2`, which in turn creates ABI incompatibility with `actix-web` unless compression is disabled. Alternatively, one of the two projects could mangle C names of statically linked library.

**Comment by Nemo157** [comment]
Moving to `brotli` from `brotli2` was done to make building the crate easier by avoiding unnecessary C dependencies (see https://github.com/Nemo157/async-compression/issues/39).

Really, the issue here is that `brotli` doesn't distinguish between being used as a Rust dependency and a static library, exporting `#[no_mangle]` functions in both cases. Opened https://github.com/dropbox/rust-brotli/issues/46 to see if this can be fixed there.

**Comment by Darkspirit** [comment]
Also, https://github.com/actix/actix-web/commit/1d12ba9d5ff691178c3fe61f3f662ca7d98080d2 should be reverted and fixed.
